name: DevSecOps Pipeline

on:
  push:
    branches: ["main"]

jobs:
  security-check:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write   # for future GitHub Security tab (SARIF)
      id-token: write          # for OIDC (future deploy)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 🐳 Build da imagem
      - name: Build Docker image
        run: docker build -t secure-api .

      # 🔍 Scan de vulnerabilidades na imagem
      - name: Run Trivy (image scan)
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          image-ref: secure-api
          severity: CRITICAL
          exit-code: 1
          format: table

      # 📦 Scan de dependências (Node.js)
      - name: Run Trivy (filesystem scan)
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL
          exit-code: 1
          format: table